# A filegroup for the test input files.
filegroup(
    name = "test_resources",
    srcs = glob(["**"]), # include all files in the directory and in all subdirectories
    visibility = ["//visibility:public"],
)